permissions:
  contents: read
name: Build Native executables

on:
  # must be triggered by build.yml
  workflow_call:
    inputs:
      head_sha:
        description: 'The commit SHA to checkout'
        required: false
        type: string

jobs:
  # Build native executable per runner
  build-native:
    strategy:
      fail-fast: true
      matrix:
        include:
          - target: macos-x64
            os: macos-15-intel
            arch: x64
          - target: macos-aarch64
            os: macos-15
            arch: aarch64
          - target: windows-x64
            os: windows-2025
            arch: x64
          - target: linux-aarch64
            os: ubuntu-24.04-arm
            arch: aarch64
          - target: linux-x64
            os: ubuntu-24.04
            arch: x64
    runs-on: ${{ matrix.os }}
    environment: native-build

    steps:
      - name: Clone repository
        uses: actions/checkout@v6.0.2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
          ref: ${{ inputs.head_sha || github.sha }}

      - name: Set up JDK
        uses: actions/setup-java@v5.2.0
        with:
          cache: maven
          distribution: 'graalvm'
          java-version: 25

      - name: Retrieve musl toolchain from cache
        id: musl-toolchain-cache
        uses: actions/cache/restore@v5.0.3
        if: ${{ contains(matrix.os, 'ubuntu') }}
        with:
          path: ~/.musl-toolchain
          key: mcs-musl-toolchain-11

      - name: Get musl toolchain and compile libz against it
        shell: bash
        id: prepare-musl
        run: |
          echo "Downloading musl toolchain and compiling zlib against it..."
          mkdir -p ~/.musl-toolchain
          pushd ~/.musl-toolchain
          
          case $MATRIX_OS in
            ubuntu-24.04)
              MUSL_TOOLCHAIN_ARCH=x86_64
              ;;
            ubuntu-24.04-arm)
              MUSL_TOOLCHAIN_ARCH=aarch64
              ;;
            *)
              echo "Unexpected CPU architecture '$MATRIX_OS'!"
              exit 1
              ;;
          esac
          
          MUSL_TOOLCHAIN_FILE=${MUSL_TOOLCHAIN_ARCH}-linux-musl-native.tgz
          TOOLCHAIN_DIR=$TMP_DIR/${MUSL_TOOLCHAIN_ARCH}-linux-musl-native
          
          if [ "$MATRIX_OS" = "ubuntu-24.04-arm" ]; then
            # Symlink x86_64-linux-musl-gcc to aarch64-linux-musl-gcc as native-image expects the former to be present
            # See https://www.graalvm.org/dev/reference-manual/native-image/guides/build-static-executables/
            ln -s $TOOLCHAIN_DIR/bin/aarch64-linux-musl-gcc $TOOLCHAIN_DIR/bin/x86_64-linux-musl-gcc
          fi

          if [ ! -f ${MUSL_TOOLCHAIN_FILE} ]; then
            curl \
                --silent \
                --insecure \
                --show-error \
                --user "${MUSL_TOOLCHAIN_USER}:${MUSL_TOOLCHAIN_PASS}" \
                --location \
                --remote-name \
                --remote-header-name \
                --url "${MUSL_TOOLCHAIN_LOCATION}/11/${MUSL_TOOLCHAIN_ARCH}-linux-musl/${MUSL_TOOLCHAIN_FILE}"
          fi
          popd
          
          TMP_DIR=$(mktemp -d)
          pushd $TMP_DIR
          tar -xvf ~/.musl-toolchain/${MUSL_TOOLCHAIN_FILE}
          
          echo "Downloading and compiling zlib 1.3..."
          curl \
            --silent \
            --show-error \
            --location \
            --remote-name \
            --remote-header-name \
            --url "https://zlib.net/zlib-1.3.2.tar.gz"
          tar -xzf zlib-1.3.2.tar.gz
          cd zlib-1.3.2
          
          TOOLCHAIN_DIR=$TMP_DIR/${MUSL_TOOLCHAIN_ARCH}-linux-musl-native
          CC=$TOOLCHAIN_DIR/bin/gcc
          
          echo "Configuring and installing zlib..."
          ./configure --prefix=$TOOLCHAIN_DIR --static
          make
          make install
          
          echo "Prepared musl toolchain at $TOOLCHAIN_DIR"
          echo "TOOLCHAIN_DIR=$TOOLCHAIN_DIR" >> $GITHUB_OUTPUT
        if: ${{ contains(matrix.os, 'ubuntu') }}
        env:
          MUSL_TOOLCHAIN_LOCATION: ${{ secrets.MUSL_TOOLCHAIN_LOCATION }}
          MUSL_TOOLCHAIN_USER: ${{ secrets.MUSL_TOOLCHAIN_USER }}
          MUSL_TOOLCHAIN_PASS: ${{ secrets.MUSL_TOOLCHAIN_PASS }}
          MATRIX_OS: ${{ matrix.os }}

      - name: Save musl toolchain to cache
        uses: actions/cache/save@v5.0.3
        if: ${{ contains(matrix.os, 'ubuntu') }}
        with:
          path: ~/.musl-toolchain
          key: mcs-musl-toolchain-11

      - name: Cache Maven packages
        id: restore-maven-package-cache
        uses: actions/cache/restore@v5.0.3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build static native image for Linux
        run: |
          PATH="${TOOLCHAIN_DIR}/bin:${PATH}"
          export PATH
          mvn -B -Pnative -Pdist verify
        env:
          TOOLCHAIN_DIR: ${{ steps.prepare-musl.outputs.TOOLCHAIN_DIR }}
        if: ${{ contains(matrix.os, 'ubuntu') }}

      - name: Build static native image for Windows / macOS
        run: |
          mvn -B -Pnative -Pdist package
        if: ${{ ! contains(matrix.os, 'ubuntu') }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v7.0.0
        with:
          name: artifacts-${{ matrix.target }}
          path: |
            target/distributions/*.zip
            target/distributions/*.tar.gz

      - name: Save downloaded Maven packages
        uses: actions/cache/save@v5.0.3
        with:
          path: ~/.m2
          key: ${{ steps.restore-maven-package-cache.outputs.cache-primary-key }}
        if: github.event.workflow_run.event != 'pull_request'
